### ISSUE TITLE
Owner field doesn’t update after transfer

### ISSUE THREAD

**Issue by edwardexo** [overextended/ox_banking#41]
**Describe the bug**
After transferring ownership of a shared account, the 'Account owner' field doesn’t immediately update to the new owner’s name. (although the account role correctly changes from Owner to Manager). To see the updated name, the UI has to be reopened.

**Framework**
OX

**Resource version**
1.0.1

**To Reproduce**
1. Create a new account
2. Convert it to a shared account
3. Transfer ownership

**Expected behaviour**
The account owner name should reflect the new owner.

**Actual behaviour**
The account owner name remains as the old owner.

**Screenshots**
Before transfer (correct):
<img src="https://github.com/user-attachments/assets/75d35c2d-326a-42de-8360-396d5b0d3538" width="768">

After transfer (wrong):
<img src="https://github.com/user-attachments/assets/b4724954-1103-40ae-9937-94d2d5a08608" width="768">

After UI re-open (correct):
<img src="https://github.com/user-attachments/assets/1e55c8c5-b57d-4a98-835e-c7d6208ca132" width="768">

**Comment by LukeWasTakenn** [comment]
Resolved in 8a3773e2654c511c7bd0bb030d6913f57539967e
