### ISSUE TITLE
[BUG] Locale imports in fxmanifest are not generalized

### ISSUE THREAD

**Issue by andreutu** [overextended/ox_banking#43]
Currently, build.js is scanning for all the files in the locales folder, and putting each one separately. In case of a new locale being added to the locales folder, that new JSON file wouldn't be recognized by the resource. I suggest generalizing this, so that all locale files are automatically recognised without the need of rebuilding the resource.

### Current Situation:
```lua
'locales/en.json',
'locales/lt.json',
'locales/nl.json',
```

### Ideal Solution:
```lua
'locales/*.json'
```

NOTE: I have (kinda) managed to solve this issue myself, however I do not think my solution is very good / I do not think I have done it properly.

Replace lines 88-89 in `build.js` ([this](https://github.com/overextended/ox_banking/blob/7be5f8d8464240e82764bc32369465ceffdccbb4/scripts/build.js#L88C1-L90C61) code).
```js
const files = await getFiles('dist/web', 'data');

fxmanifest += `\nfiles {\n\t'${files.join("',\n\t'")}',\n\t'locales/*.json'\n}`;
```

**Comment by LukeWasTakenn** [comment]
Should be resolved in 7e93a1992fa95dde3234a607ef76be5812774243
